spring:
  application:
    active: dev
---	
server:
  port: 7001
  
spring:
   profiles: dev
   application: 
     name: microservicecloud-euraka-config-dev  
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false  #false
    fetch-registry: false   #false
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka
---
server:
  port: 7002
  
spring:
   profiles: test
   application: 
     name: microservicecloud-euraka-config-test  
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false  #false
    fetch-registry: false   #false
    service-url:
       defaultZone: http://eureka7002.com:7002/eureka